### ISSUE TITLE
Refactor Create User endpoint

### ISSUE THREAD

**Issue by vladyslav-bezpalko** [2DLenin/drfblog#4]
https://github.com/2DLenin/drfblog/blob/b7d4722acf83c3e9859bef61ef498afe7be3a568/littleblog/entry/views.py#L15-L35

1. You did override all useful methods provided by `CreateAPIView` so it became useless actually. It's better to not override post/create methods - they're pretty generic and we can make use of `CreateAPIView` without overriding them. The only thing you usually need to implement/override is `perform_create` here.

2. This code contains a major bug. Try to test it by yourself - make a request in the way that validation of `UserProfileCreateSerializer`  fails. For example, pass the nickname that is longer than 255 characters. You should get an API error response. But you can also notice weird behavior if you will look in your users db table after :) 
Let's discuss this after you find the issue.

3. If you're using username and password from `request.data` - they should go through serializer, i.e you should validate them. Otherwise, you may have bad data in db, or the `create_user` operation will fail with the exception (HTTP 500 server error) in some edge cases. Add username and password to your serializer instead of `user = PKField`. `UserProfileCreateSerializer` should contain all fields needed to create a user - API user shouldn't be required to provide `user` field, because there's no way to create `user` other than through this API.

**Comment by Stanislav-Lykhachov** [comment]
> 2. This code contains a major bug. Try to test it by yourself - make a request in the way that validation of `UserProfileCreateSerializer`  fails. For example, pass the nickname that is longer than 255 characters. You should get an API error response. But you can also notice weird behavior if you will look in your users db table after :)

Thx, I have already figured this out. Even if serializer.is_valid == False and UserProfile is not created, although User instance was created in the previous part of code :D
